eureka:
  instance:
    prefer-ip-address: false
    hostname: ${EUREKA_HOSTNAME:localhost}
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

management:
  tracing:
    sampling:
      probability: 1.0
